# Ref: https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/go#configuration-file

version: 1
goos: windows
goarch: arm64
env:
  - CGO_ENABLED=0
flags:
  - -trimpath
binary: serve-dir-windows-arm64
