# Copyright 2023 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

# Ref: https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/go#configuration-file

version: 1
goos: windows
goarch: amd64
env:
  - CGO_ENABLED=0
flags:
  - -trimpath
binary: windows-amd64/serve-dir.exe
