# Copyright 2023 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

# Ref: https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/go

name: SLSA Go releaser
on:
  workflow_dispatch:
  # We want to create the binaries as soon as the tag is pushed, not after the
  # release is created. When the release is created, it's immediately live. This
  # means that users will be confused by having a release but no binary will be
  # available until the builds are done; this is a race condition.
  #
  # We can alleviate this by pushing the tag first, causing the builds start
  # right away. One winkle is that github will create a release as soon as one
  # binary is uploaded.
  #
  #release:
  #  types: [created]
  push:
    tags:
      - "*"

permissions: read-all

jobs:
  args:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

  build:
    permissions:
      id-token: write # To sign.
      contents: write # To upload release assets.
      actions: read   # To read workflow path.
    strategy:
      fail-fast: false
      matrix:
        os:
          - darwin
          - linux
          - windows
        arch:
          - amd64
          - arm64
    needs: args
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.9.0
    with:
      go-version: 1.21
      config-file: .github/slsa-${{matrix.os}}-${{matrix.arch}}.yml
      evaluated-envs: "GOOS:${{matrix.os}}, GOARCH:${{matrix.arch}}"
